// Wave-N (ADR-039 + ADR-041) test suite — cross-impl byte-equivalence with the
// canonical Rust verifier at `governance/rzl/src/wave_n.rs` and
// `tools/nanorix-verify/src/lib.rs`.
//
// **Forever-Standard discipline (ADR-006 I0):** every test here pins a
// cryptographic-attestation contract. Any divergence from the Rust reference
// vectors is a P0 finding.
//
// Cross-impl reference vectors (generated by
// `cargo run --package nanorix-rzl --example gen_wave_n_vectors`) are
// hard-coded into `TestCrossImplReferenceVector*` tests below.

package auditproof

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha512"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"
	"testing"
)

const (
	waveNTimestamp = "2026-05-12T00:00:00Z"
	waveNCapsuleID = "cap_wave_n_fixture"
)

// ─────────────────────────────────────────────────────────────────────────────
// Cross-impl reference-vector regression
//
// These hashes are generated by the canonical Rust implementation at
// `governance/rzl/src/wave_n.rs` via the
// `governance/rzl/examples/gen_wave_n_vectors` example. Any Go-side drift from
// these values is a Forever-Standard ADR-006 I0 violation.
// ─────────────────────────────────────────────────────────────────────────────

func TestCrossImplReferenceVectorGenesisHash(t *testing.T) {
	// SHA-512 of the empty string. Mirror of Rust constant
	// `nanorix_rzl::wave_n::GENESIS_SHA512_HEX`.
	const wantGenesis = "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"
	if NanorixGenesisHash != wantGenesis {
		t.Fatalf("GENESIS_SHA512_HEX drift: got %s, want %s", NanorixGenesisHash, wantGenesis)
	}
}

func TestCrossImplReferenceVectorMerklePairHash(t *testing.T) {
	// Vector 1: MerklePairHash("aaa", "bbb") ==
	//   SHA-512("aaa" || \x00 || "bbb") in hex.
	const wantAaaBbb = "04ed285cc0e9fe4331e8248f8c37601f4a0836fe1b712fd45096ddd9acdcac1f088ce35db15a93bbc9d13bd7683a2483ab0adbda35814d17f1d44942bf9bd264"
	if got := MerklePairHash("aaa", "bbb"); got != wantAaaBbb {
		t.Errorf("MerklePairHash(aaa, bbb) drift: got %s, want %s", got, wantAaaBbb)
	}

	// Vector 2: deadbeef + cafebabe.
	const wantDeadCafe = "457bce5b50593c263df032ff497826848beaa70fcfb7d9e63ed780f994ed58958ddea9e898f27c3b03a7bc8db879aee658f9ef934bc7c987765fd02b7c6ea978"
	if got := MerklePairHash("deadbeef", "cafebabe"); got != wantDeadCafe {
		t.Errorf("MerklePairHash(deadbeef, cafebabe) drift: got %s, want %s", got, wantDeadCafe)
	}

	// Vector 3: prefix tolerance — sha512:aaa + bbb should equal aaa + bbb.
	if got := MerklePairHash("sha512:aaa", "bbb"); got != wantAaaBbb {
		t.Errorf("MerklePairHash prefix-strip drift: got %s, want %s", got, wantAaaBbb)
	}
}

func TestCrossImplReferenceVectorRecordChainHash(t *testing.T) {
	const wantChain = "sha512:c83d2311b8d3d0d5c20e920773e2e3a56c08bdd2e7d142ce13a0e9702487b679a8cddebb7f4d87b0e1ad7f8d2d2343a0b64f085ae092672c1d2145a1b9653660"
	got := ComputeRecordChainHash(
		"cap_test",
		0,
		"rec_abc",
		"sha512:deadbeef",
		"sha512:cafebabe",
		NanorixGenesisHash,
		nil,
	)
	if got != wantChain {
		t.Errorf("ComputeRecordChainHash basic drift: got %s, want %s", got, wantChain)
	}
}

func TestCrossImplReferenceVectorStep8AmendedAllArms(t *testing.T) {
	prev := NanorixGenesisHash
	ts := "2026-05-12T00:00:00Z"

	cases := []struct {
		name string
		rrmr *string
		ppmr *string
		want string
	}{
		{
			name: "(None, None) — pre-Wave-N legacy byte-equivalent",
			rrmr: nil,
			ppmr: nil,
			want: "3b6a0c8fa70b0e1ead6d2c4c44050c3a45bb732dcd24ff71ffa284a034d5bc41ad4408f4c20649b76ce9a2a8885e857b13ad134f38c92abafb4700b2129b3fbf",
		},
		{
			name: "(Some(sha512:deadbeef), None) — ADR-039 only",
			rrmr: strPtrLocal("sha512:deadbeef"),
			ppmr: nil,
			want: "9e8cd988effabfaf0143a917c9a34f7449290a122babd440db9a3a7983f8783e180f3d0ad1010c5af11ba16d82ff5dd12b102e93ed27f070a1b535fd27509bf1",
		},
		{
			name: "(None, Some(sha512:cafebabe)) — ADR-041 only",
			rrmr: nil,
			ppmr: strPtrLocal("sha512:cafebabe"),
			want: "39b163c4cc38be18dbc4b5b715b1914a738077633a8155f052c2b8e952073ab3b567010673718e4a6f451f9c3eb1bf508e3205cb1fd5a26019f9782ca55113f8",
		},
		{
			name: "(Some, Some) — combined ADR-039 + ADR-041",
			rrmr: strPtrLocal("sha512:deadbeef"),
			ppmr: strPtrLocal("sha512:cafebabe"),
			want: "81c5f049bfb0f7b7e534a297d4d6a8e07704deeb97557827987cf1688a6e189ef07a375c3dcf6d8ad954a0838eecd8c9c5702a6124e8c07a0f1aeffd6e38b844",
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := ComputeStep8Amended(prev, ts, c.rrmr, c.ppmr)
			if got != c.want {
				t.Errorf("Step 8 %s drift:\n  got=%s\n want=%s", c.name, got, c.want)
			}
		})
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Forever-Standard byte-equivalence with pre-Wave-N legacy formula
// ─────────────────────────────────────────────────────────────────────────────

func TestStep8AmendedNoneNoneByteEquivalence(t *testing.T) {
	// The LOAD-BEARING test: when neither receipts nor parents present, Step 8
	// MUST be byte-identical to the pre-Wave-N legacy `ComputeStepHash`. Every
	// pre-Wave-N AuditProof on the 100-fixture corpus depends on this.
	prev := NanorixGenesisHash
	ts := "2026-05-12T00:00:00Z"

	legacy := ComputeStepHash(prev, "capsule_destroy", "destroy", "capsule_lifecycle_verification", ts)
	amended := ComputeStep8Amended(prev, ts, nil, nil)

	if legacy != amended {
		t.Fatalf("Forever-Standard violation: (nil, nil) MUST equal legacy formula\n  legacy=%s\n  amended=%s", legacy, amended)
	}
}

func TestStep8AmendedDivergesWithReceiptsPresent(t *testing.T) {
	prev := NanorixGenesisHash
	ts := "2026-05-12T00:00:00Z"

	base := ComputeStep8Amended(prev, ts, nil, nil)
	withRR := ComputeStep8Amended(prev, ts, strPtrLocal("sha512:deadbeef"), nil)
	if base == withRR {
		t.Fatalf("Presence of rrmr MUST shift Step 8 hash")
	}
}

func TestStep8AmendedDivergesWithParentsPresent(t *testing.T) {
	prev := NanorixGenesisHash
	ts := "2026-05-12T00:00:00Z"

	base := ComputeStep8Amended(prev, ts, nil, nil)
	withPP := ComputeStep8Amended(prev, ts, nil, strPtrLocal("sha512:cafebabe"))
	if base == withPP {
		t.Fatalf("Presence of ppmr MUST shift Step 8 hash")
	}
}

func TestStep8AmendedAllArmsDistinct(t *testing.T) {
	prev := NanorixGenesisHash
	ts := "2026-05-12T00:00:00Z"
	rr := "sha512:1111"
	pp := "sha512:2222"

	rrOnly := ComputeStep8Amended(prev, ts, strPtrLocal(rr), nil)
	ppOnly := ComputeStep8Amended(prev, ts, nil, strPtrLocal(pp))
	both := ComputeStep8Amended(prev, ts, strPtrLocal(rr), strPtrLocal(pp))

	if rrOnly == both {
		t.Errorf("rrOnly must differ from both")
	}
	if ppOnly == both {
		t.Errorf("ppOnly must differ from both")
	}
	if rrOnly == ppOnly {
		t.Errorf("rrOnly must differ from ppOnly")
	}
}

func TestStep8AmendedPrefixTolerance(t *testing.T) {
	prev := NanorixGenesisHash
	ts := "2026-05-12T00:00:00Z"

	a := ComputeStep8Amended(prev, ts, strPtrLocal("sha512:deadbeef"), nil)
	b := ComputeStep8Amended(prev, ts, strPtrLocal("deadbeef"), nil)
	if a != b {
		t.Errorf("Prefix tolerance broken:\n  with prefix=%s\n  no prefix=%s", a, b)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Merkle root construction
// ─────────────────────────────────────────────────────────────────────────────

func TestMerkleRootN0ReturnsNone(t *testing.T) {
	_, ok := MerkleRootSHA512NullSeparated(nil)
	if ok {
		t.Fatal("N=0 must return (\"\", false)")
	}
}

func TestMerkleRootN1EqualsLeaf(t *testing.T) {
	root, ok := MerkleRootSHA512NullSeparated([]string{"sha512:abc123"})
	if !ok {
		t.Fatal("N=1 must return (leaf, true)")
	}
	if root != "abc123" {
		t.Errorf("N=1 root must equal leaf stripped: got %s, want abc123", root)
	}
}

func TestMerkleRootN2IsPairHash(t *testing.T) {
	root, ok := MerkleRootSHA512NullSeparated([]string{"sha512:aaa", "sha512:bbb"})
	if !ok {
		t.Fatal("N=2 root expected")
	}
	want := MerklePairHash("aaa", "bbb")
	if root != want {
		t.Errorf("N=2 root drift: got %s, want %s", root, want)
	}
}

func TestMerkleRootN3UsesOddDuplication(t *testing.T) {
	// Three leaves: a, b, c
	// Level 0: [a, b, c]
	// Level 1: [pair(a,b), pair(c,c)]
	// Level 2: [pair(pair(a,b), pair(c,c))] = root
	root, ok := MerkleRootSHA512NullSeparated([]string{"aaa", "bbb", "ccc"})
	if !ok {
		t.Fatal("N=3 root expected")
	}
	lvl1Left := MerklePairHash("aaa", "bbb")
	lvl1Right := MerklePairHash("ccc", "ccc")
	want := MerklePairHash(lvl1Left, lvl1Right)
	if root != want {
		t.Errorf("N=3 odd-duplication root drift: got %s, want %s", root, want)
	}
}

func TestMerkleRootDeterministic(t *testing.T) {
	leaves := make([]string, 7)
	for i := range leaves {
		leaves[i] = fmt.Sprintf("leaf_%02d", i)
	}
	r1, ok1 := MerkleRootSHA512NullSeparated(leaves)
	r2, ok2 := MerkleRootSHA512NullSeparated(leaves)
	if !ok1 || !ok2 || r1 != r2 {
		t.Fatalf("Merkle root must be deterministic: r1=%s, r2=%s", r1, r2)
	}
}

func TestMerkleRootReorderBreaksRoot(t *testing.T) {
	leaves := []string{"a", "b", "c", "d", "e"}
	r1, _ := MerkleRootSHA512NullSeparated(leaves)

	leaves[0], leaves[4] = leaves[4], leaves[0]
	r2, _ := MerkleRootSHA512NullSeparated(leaves)
	if r1 == r2 {
		t.Errorf("Leaf reorder must change Merkle root")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Inclusion proof
// ─────────────────────────────────────────────────────────────────────────────

func TestInclusionProofN1Empty(t *testing.T) {
	leaves := []string{"sha512:onlyleaf"}
	proof, ok := BuildMerkleInclusionProof(leaves, 0)
	if !ok {
		t.Fatal("BuildMerkleInclusionProof N=1 idx=0 must succeed")
	}
	if len(proof) != 0 {
		t.Errorf("N=1 inclusion proof must be empty, got %d entries", len(proof))
	}
	root, _ := MerkleRootSHA512NullSeparated(leaves)
	if !VerifyMerkleInclusionProof("onlyleaf", 0, proof, root) {
		t.Error("Empty inclusion proof must verify when leaf == root")
	}
}

func TestInclusionProofN2Roundtrips(t *testing.T) {
	leaves := []string{"aaa", "bbb"}
	root, _ := MerkleRootSHA512NullSeparated(leaves)
	p0, _ := BuildMerkleInclusionProof(leaves, 0)
	p1, _ := BuildMerkleInclusionProof(leaves, 1)
	if !VerifyMerkleInclusionProof("aaa", 0, p0, root) {
		t.Error("N=2 leaf 0 inclusion must verify")
	}
	if !VerifyMerkleInclusionProof("bbb", 1, p1, root) {
		t.Error("N=2 leaf 1 inclusion must verify")
	}
	// Wrong leaf must fail.
	if VerifyMerkleInclusionProof("xxx", 0, p0, root) {
		t.Error("Inclusion proof MUST NOT verify for wrong leaf")
	}
}

func TestInclusionProofN10EachLeafRoundtrips(t *testing.T) {
	leaves := make([]string, 10)
	for i := range leaves {
		leaves[i] = fmt.Sprintf("leaf_%03d", i)
	}
	root, _ := MerkleRootSHA512NullSeparated(leaves)
	for i, leaf := range leaves {
		proof, ok := BuildMerkleInclusionProof(leaves, i)
		if !ok {
			t.Fatalf("BuildMerkleInclusionProof idx=%d failed", i)
		}
		if !VerifyMerkleInclusionProof(leaf, i, proof, root) {
			t.Errorf("leaf %d inclusion proof must roundtrip", i)
		}
	}
}

func TestInclusionProofOutOfRangeIsNone(t *testing.T) {
	leaves := []string{"a", "b"}
	if _, ok := BuildMerkleInclusionProof(leaves, 5); ok {
		t.Error("Out-of-range leaf_index must return (_, false)")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Record chain hash field-binding properties
// ─────────────────────────────────────────────────────────────────────────────

func TestRecordChainHashDeterministic(t *testing.T) {
	h1 := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in", "sha512:out", NanorixGenesisHash, nil)
	h2 := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in", "sha512:out", NanorixGenesisHash, nil)
	if h1 != h2 {
		t.Fatalf("record_chain_hash must be deterministic: %s != %s", h1, h2)
	}
	if !strings.HasPrefix(h1, "sha512:") {
		t.Errorf("record_chain_hash must carry sha512: prefix, got %s", h1)
	}
}

func TestRecordChainHashRecordIDBinds(t *testing.T) {
	h1 := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in", "sha512:out", NanorixGenesisHash, nil)
	h2 := ComputeRecordChainHash("cap_x", 0, "rec_b", "sha512:in", "sha512:out", NanorixGenesisHash, nil)
	if h1 == h2 {
		t.Errorf("record_id must bind into chain hash")
	}
}

func TestRecordChainHashInputBinds(t *testing.T) {
	h1 := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in_1", "sha512:out", NanorixGenesisHash, nil)
	h2 := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in_2", "sha512:out", NanorixGenesisHash, nil)
	if h1 == h2 {
		t.Errorf("record_input_hash must bind")
	}
}

func TestRecordChainHashOutputBinds(t *testing.T) {
	h1 := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in", "sha512:o_1", NanorixGenesisHash, nil)
	h2 := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in", "sha512:o_2", NanorixGenesisHash, nil)
	if h1 == h2 {
		t.Errorf("record_output_hash must bind")
	}
}

func TestRecordChainHashIndexBinds(t *testing.T) {
	h1 := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in", "sha512:out", NanorixGenesisHash, nil)
	h2 := ComputeRecordChainHash("cap_x", 1, "rec_a", "sha512:in", "sha512:out", NanorixGenesisHash, nil)
	if h1 == h2 {
		t.Errorf("record_index must bind")
	}
}

func TestRecordChainHashCapsuleBinds(t *testing.T) {
	h1 := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in", "sha512:out", NanorixGenesisHash, nil)
	h2 := ComputeRecordChainHash("cap_y", 0, "rec_a", "sha512:in", "sha512:out", NanorixGenesisHash, nil)
	if h1 == h2 {
		t.Errorf("capsule_id must bind")
	}
}

func TestRecordChainHashPrefixTolerance(t *testing.T) {
	withPrefix := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:deadbeef", "sha512:cafebabe", NanorixGenesisHash, nil)
	noPrefix := ComputeRecordChainHash("cap_x", 0, "rec_a", "deadbeef", "cafebabe", NanorixGenesisHash, nil)
	if withPrefix != noPrefix {
		t.Errorf("Hash should strip sha512: prefix from inputs:\n  with=%s\n  no=%s", withPrefix, noPrefix)
	}
}

// ADR-039 conformance (mirrors Rust `record_chain_hash_pattern_tag_binds`):
// a declared pattern_tag is a SIGNED primitive — it must change the chain
// hash, else it could be swapped without invalidating the signature-anchored
// Merkle ladder.
func TestRecordChainHashPatternTagBinds(t *testing.T) {
	base := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in", "sha512:out", NanorixGenesisHash, nil)
	tagged := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in", "sha512:out", NanorixGenesisHash, strPtrLocal("pa"))
	retagged := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in", "sha512:out", NanorixGenesisHash, strPtrLocal("extraction"))
	if base == tagged {
		t.Errorf("declared tag must bind into the hash")
	}
	if tagged == retagged {
		t.Errorf("different tags must produce different hashes")
	}
}

// "No tag = old bytes": the nil-tag output must equal the manually computed
// pre-fix preimage (no trailing \x00+tag segment). Together with the pinned
// cross-impl vector in TestCrossImplReferenceVectorRecordChainHash this locks
// the untagged formula to its pre-fix byte layout.
func TestRecordChainHashNilTagKeepsPreFixBytes(t *testing.T) {
	preimage := "cap_x\x000\x00rec_a\x00in\x00out\x00" + NanorixGenesisHash
	sum := sha512.Sum512([]byte(preimage))
	want := "sha512:" + hex.EncodeToString(sum[:])
	got := ComputeRecordChainHash("cap_x", 0, "rec_a", "sha512:in", "sha512:out", NanorixGenesisHash, nil)
	if got != want {
		t.Errorf("nil-tag formula drift from pre-fix bytes: got %s, want %s", got, want)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Activity root
// ─────────────────────────────────────────────────────────────────────────────

func TestActivityRootEmptyIsGenesis(t *testing.T) {
	if got := ComputeActivityRoot(nil); got != NanorixGenesisHash {
		t.Errorf("nil trail must return genesis, got %s", got)
	}
	if got := ComputeActivityRoot([]any{}); got != NanorixGenesisHash {
		t.Errorf("empty trail must return genesis, got %s", got)
	}
}

func TestActivityRootSingleEventDiffersFromGenesis(t *testing.T) {
	trail := []any{
		map[string]any{"event": "step_completed", "step": 1},
	}
	got := ComputeActivityRoot(trail)
	if got == NanorixGenesisHash {
		t.Errorf("Single event must differ from genesis")
	}
}

func TestActivityRootOrderMatters(t *testing.T) {
	trail1 := []any{
		map[string]any{"event": "a"},
		map[string]any{"event": "b"},
	}
	trail2 := []any{
		map[string]any{"event": "b"},
		map[string]any{"event": "a"},
	}
	if ComputeActivityRoot(trail1) == ComputeActivityRoot(trail2) {
		t.Errorf("Activity event order MUST bind into root")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Cycle detection + depth cap
// ─────────────────────────────────────────────────────────────────────────────

func TestCycleDetectionRejectsSelfReference(t *testing.T) {
	parents := []ParentProofLink{
		{
			ParentChainHash: "sha512:abc",
			ParentKeyID:     "k",
			ParentSignature: "base64:s",
		},
	}
	if got := DetectParentProofCycle(parents, "sha512:abc"); got != 0 {
		t.Errorf("cycle detection must return idx 0; got %d", got)
	}
}

func TestCycleDetectionAcceptsDistinct(t *testing.T) {
	parents := []ParentProofLink{
		{
			ParentChainHash: "sha512:abc",
			ParentKeyID:     "k",
			ParentSignature: "base64:s",
		},
	}
	if got := DetectParentProofCycle(parents, "sha512:xyz"); got != -1 {
		t.Errorf("distinct parent must return -1; got %d", got)
	}
}

func TestCycleDetectionPrefixTolerance(t *testing.T) {
	parents := []ParentProofLink{
		{ParentChainHash: "abc", ParentKeyID: "k", ParentSignature: "base64:s"},
	}
	if DetectParentProofCycle(parents, "sha512:abc") != 0 {
		t.Errorf("prefix tolerance broken (sha512: on self)")
	}
	if DetectParentProofCycle(parents, "abc") != 0 {
		t.Errorf("prefix tolerance broken (bare on self)")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Property-style cycle rejection (10 iter — Go iteration is slower than Rust;
// budget is calibrated to remain under 1s in the test harness while still
// exercising the codepath with deterministic input variation)
// ─────────────────────────────────────────────────────────────────────────────

func TestCycleRejection10Iter(t *testing.T) {
	// Deterministic LCG seed; matches the Rust 10k iter pattern at smaller
	// scale to keep Go test wall time bounded.
	var state uint64 = 0xFEEDBEEFDEADC0DE
	next := func() uint64 {
		state = state*6364136223846793005 + 1442695040888963407
		return state
	}

	for iter := 0; iter < 10; iter++ {
		r := next()
		selfHash := fmt.Sprintf("sha512:%x", r)
		parents := []ParentProofLink{
			{
				ParentChainHash: selfHash, // self-reference → cycle
				ParentKeyID:     fmt.Sprintf("k_%d", iter),
				ParentSignature: "base64:malicious",
			},
		}
		if got := DetectParentProofCycle(parents, selfHash); got != 0 {
			t.Errorf("iter %d: cycle MUST fire on self-reference; got %d", iter, got)
		}
	}
}

func TestDepthCapAcceptsAt32(t *testing.T) {
	parents := make([]ParentProofLink, 32)
	for i := range parents {
		parents[i].ParentChainHash = fmt.Sprintf("sha512:p%d", i)
		parents[i].ParentKeyID = fmt.Sprintf("k_%d", i)
		parents[i].ParentSignature = "base64:s"
	}
	if err := EnforceDepthCap(parents); err != nil {
		t.Errorf("Exactly 32 parents must be accepted; got error: %v", err)
	}
}

func TestDepthCapRejectsAt33(t *testing.T) {
	parents := make([]ParentProofLink, 33)
	for i := range parents {
		parents[i].ParentChainHash = fmt.Sprintf("sha512:p%d", i)
		parents[i].ParentKeyID = fmt.Sprintf("k_%d", i)
		parents[i].ParentSignature = "base64:s"
	}
	if err := EnforceDepthCap(parents); err == nil {
		t.Errorf("33 parents must be rejected by depth cap")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Mode B — Standalone receipt verification
// ─────────────────────────────────────────────────────────────────────────────

func TestVerifyRecordReceiptModeBHappyPath(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("key gen: %v", err)
	}

	// Build a single-record receipt; N=1 → root = leaf, inclusion proof empty.
	capsuleID := waveNCapsuleID
	in := sha512Sum([]byte("input_data_0"))
	out := sha512Sum([]byte("output_data_0"))
	activityRoot := NanorixGenesisHash
	chainHash := ComputeRecordChainHash(capsuleID, 0, "rec_0", in, out, activityRoot, nil)

	receipt := RecordReceipt{
		RecordIndex:          0,
		RecordID:             "rec_0",
		RecordInputHash:      "sha512:" + in,
		RecordOutputHash:     "sha512:" + out,
		RecordChainHash:      chainHash,
		MerkleInclusionProof: []string{},
	}

	// Outer chain hash arbitrary; signature is over its ASCII-hex bytes.
	outerChainHash := strings.Repeat("a", 128)
	sig := ed25519.Sign(priv, []byte(outerChainHash))
	sigB64 := base64.StdEncoding.EncodeToString(sig)

	opts := VerifyRecordReceiptOptions{
		CapsuleID:         capsuleID,
		OuterMerkleRoot:   chainHash, // N=1 root = leaf
		OuterChainHash:    "sha512:" + outerChainHash,
		OuterSignatureB64: "base64:" + sigB64,
		OuterPublicKey:    pub,
	}
	if err := VerifyRecordReceipt(receipt, opts); err != nil {
		t.Errorf("happy-path Mode B verification must succeed; got: %v", err)
	}
}

func TestVerifyRecordReceiptModeBTaggedHappyPath(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("key gen: %v", err)
	}

	// Tagged single-record receipt; N=1 → root = leaf, inclusion proof empty.
	capsuleID := waveNCapsuleID
	in := sha512Sum([]byte("input_data_tagged"))
	out := sha512Sum([]byte("output_data_tagged"))
	tag := "rcm_claim"
	chainHash := ComputeRecordChainHash(capsuleID, 0, "rec_0", in, out, NanorixGenesisHash, &tag)

	receipt := RecordReceipt{
		RecordIndex:          0,
		RecordID:             "rec_0",
		RecordInputHash:      "sha512:" + in,
		RecordOutputHash:     "sha512:" + out,
		RecordChainHash:      chainHash,
		PatternTag:           &tag,
		MerkleInclusionProof: []string{},
	}

	outerChainHash := strings.Repeat("a", 128)
	sig := ed25519.Sign(priv, []byte(outerChainHash))

	opts := VerifyRecordReceiptOptions{
		CapsuleID:         capsuleID,
		OuterMerkleRoot:   chainHash,
		OuterChainHash:    "sha512:" + outerChainHash,
		OuterSignatureB64: "base64:" + base64.StdEncoding.EncodeToString(sig),
		OuterPublicKey:    pub,
	}
	if err := VerifyRecordReceipt(receipt, opts); err != nil {
		t.Errorf("tagged Mode B verification must succeed; got: %v", err)
	}

	// Tag swap after signing must invalidate the recompute.
	swapped := "custom"
	receipt.PatternTag = &swapped
	if err := VerifyRecordReceipt(receipt, opts); err == nil {
		t.Errorf("swapped pattern_tag MUST be rejected in Mode B")
	}

	// Tag strip must also invalidate (tagged hash != untagged hash).
	receipt.PatternTag = nil
	if err := VerifyRecordReceipt(receipt, opts); err == nil {
		t.Errorf("stripped pattern_tag MUST be rejected in Mode B")
	}
}

func TestVerifyRecordReceiptModeBRejectsTamperedChainHash(t *testing.T) {
	pub, _, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("key gen: %v", err)
	}
	receipt := RecordReceipt{
		RecordIndex:          0,
		RecordID:             "rec_0",
		RecordInputHash:      "sha512:" + sha512Sum([]byte("in")),
		RecordOutputHash:     "sha512:" + sha512Sum([]byte("out")),
		RecordChainHash:      "sha512:" + strings.Repeat("f", 128), // tampered
		MerkleInclusionProof: []string{},
	}
	opts := VerifyRecordReceiptOptions{
		CapsuleID:         waveNCapsuleID,
		OuterMerkleRoot:   receipt.RecordChainHash,
		OuterChainHash:    "sha512:" + strings.Repeat("a", 128),
		OuterSignatureB64: "base64:" + base64.StdEncoding.EncodeToString(make([]byte, ed25519.SignatureSize)),
		OuterPublicKey:    pub,
	}
	if err := VerifyRecordReceipt(receipt, opts); err == nil {
		t.Errorf("tampered chain hash MUST be rejected")
	} else if !strings.Contains(err.Error(), "record_chain_hash mismatch") {
		t.Errorf("expected chain hash mismatch error; got: %v", err)
	}
}

func TestVerifyRecordReceiptModeBRejectsBadInclusionProof(t *testing.T) {
	pub, _, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("key gen: %v", err)
	}
	in := sha512Sum([]byte("in_0"))
	out := sha512Sum([]byte("out_0"))
	chainHash := ComputeRecordChainHash(waveNCapsuleID, 0, "rec_0", in, out, NanorixGenesisHash, nil)
	receipt := RecordReceipt{
		RecordIndex:          0,
		RecordID:             "rec_0",
		RecordInputHash:      "sha512:" + in,
		RecordOutputHash:     "sha512:" + out,
		RecordChainHash:      chainHash,
		MerkleInclusionProof: []string{},
	}
	// Outer Merkle root is DIFFERENT from the receipt's own chain hash; N=1
	// inclusion check requires leaf == root, so this fails.
	opts := VerifyRecordReceiptOptions{
		CapsuleID:         waveNCapsuleID,
		OuterMerkleRoot:   "sha512:" + strings.Repeat("c", 128),
		OuterChainHash:    "sha512:" + strings.Repeat("a", 128),
		OuterSignatureB64: "base64:" + base64.StdEncoding.EncodeToString(make([]byte, ed25519.SignatureSize)),
		OuterPublicKey:    pub,
	}
	if err := VerifyRecordReceipt(receipt, opts); err == nil {
		t.Errorf("inclusion proof mismatch MUST be rejected")
	}
}

func TestVerifyRecordReceiptModeBRejectsBadSignature(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("key gen: %v", err)
	}
	in := sha512Sum([]byte("in_0"))
	out := sha512Sum([]byte("out_0"))
	chainHash := ComputeRecordChainHash(waveNCapsuleID, 0, "rec_0", in, out, NanorixGenesisHash, nil)
	receipt := RecordReceipt{
		RecordIndex:          0,
		RecordID:             "rec_0",
		RecordInputHash:      "sha512:" + in,
		RecordOutputHash:     "sha512:" + out,
		RecordChainHash:      chainHash,
		MerkleInclusionProof: []string{},
	}
	// Sign a DIFFERENT chain hash than what the verifier checks.
	differentMsg := strings.Repeat("b", 128)
	sig := ed25519.Sign(priv, []byte(differentMsg))
	opts := VerifyRecordReceiptOptions{
		CapsuleID:         waveNCapsuleID,
		OuterMerkleRoot:   chainHash,
		OuterChainHash:    "sha512:" + strings.Repeat("a", 128),
		OuterSignatureB64: "base64:" + base64.StdEncoding.EncodeToString(sig),
		OuterPublicKey:    pub,
	}
	if err := VerifyRecordReceipt(receipt, opts); err == nil {
		t.Errorf("wrong signature MUST be rejected")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Mode A — Full Wave-N AuditProof verification
// ─────────────────────────────────────────────────────────────────────────────

// buildWaveNProof creates a Wave-N AuditProof with N receipts + M parent
// links, mirroring `tools/nanorix-verify/tests/wave_n_fixtures.rs::
// synthesize_wave_n_proof`.
func buildWaveNProof(nReceipts int, parentSeeds [][]string) map[string]interface{} {
	subsystems := []string{
		"eee_namespace", "eee_tmpfs", "eee_memory", "dire_keys",
		"dire_identity", "fgx_forensic", "rzl_audit", "capsule_destroy",
	}

	// Build receipts.
	receipts := make([]interface{}, 0, nReceipts)
	leafChainHashes := make([]string, 0, nReceipts)
	for i := 0; i < nReceipts; i++ {
		inH := sha512Sum([]byte(fmt.Sprintf("in_%d", i)))
		outH := sha512Sum([]byte(fmt.Sprintf("out_%d", i)))
		activityRoot := NanorixGenesisHash
		recordID := fmt.Sprintf("rec_%05d", i)

		var patternTag string
		switch i % 4 {
		case 0:
			patternTag = "pa"
		case 1:
			patternTag = "rcm_claim"
		case 2:
			patternTag = "dicom_study"
		default:
			patternTag = "agent_step"
		}
		// ADR-039: the declared tag is a signed primitive — bound into the
		// per-record chain hash, not merely carried in the JSON.
		chainH := ComputeRecordChainHash(waveNCapsuleID, uint32(i), recordID, inH, outH, activityRoot, strPtrLocal(patternTag))
		receipts = append(receipts, map[string]interface{}{
			"record_index":           i,
			"record_id":              recordID,
			"record_input_hash":      "sha512:" + inH,
			"record_output_hash":     "sha512:" + outH,
			"record_chain_hash":      chainH,
			"pattern_tag":            patternTag,
			"merkle_inclusion_proof": []string{},
		})
		leafChainHashes = append(leafChainHashes, chainH)
	}

	var rrmrPtr *string
	if len(leafChainHashes) > 0 {
		root, ok := MerkleRootSHA512NullSeparated(leafChainHashes)
		if ok {
			full := "sha512:" + root
			rrmrPtr = &full
		}
	}

	// Build parents.
	parents := make([]interface{}, 0, len(parentSeeds))
	parentLeaves := make([]string, 0, len(parentSeeds))
	for i, seed := range parentSeeds {
		role := seed[0]
		org := seed[1]
		chainH := sha512Sum([]byte(fmt.Sprintf("parent_%d", i)))
		sig := sha512Sum([]byte(fmt.Sprintf("sig_%d", i)))
		parents = append(parents, map[string]interface{}{
			"parent_chain_hash":       "sha512:" + chainH,
			"parent_key_id":           fmt.Sprintf("cust-auth-%s-%d", role, i),
			"parent_signature":        "base64:" + sig,
			"parent_role":             role,
			"parent_jurisdiction":     "US",
			"parent_organization_tag": fmt.Sprintf("vendor:%s", org),
		})
		parentLeaves = append(parentLeaves, "sha512:"+chainH)
	}
	var ppmrPtr *string
	if len(parentLeaves) > 0 {
		root, ok := MerkleRootSHA512NullSeparated(parentLeaves)
		if ok {
			full := "sha512:" + root
			ppmrPtr = &full
		}
	}

	// Build chain steps 1-7 legacy, step 8 amended.
	prevHash := NanorixGenesisHash
	chain := make([]interface{}, 0, 8)
	for i, subsystem := range subsystems {
		method := LookupMethod(subsystem)
		var chainHash string
		if i == 7 {
			chainHash = ComputeStep8Amended(prevHash, waveNTimestamp, rrmrPtr, ppmrPtr)
		} else {
			chainHash = ComputeStepHash(prevHash, subsystem, "destroy", method, waveNTimestamp)
		}
		chain = append(chain, map[string]interface{}{
			"subsystem":  subsystem,
			"method":     method,
			"chain_hash": chainHash,
		})
		prevHash = chainHash
	}
	finalHash := chain[7].(map[string]interface{})["chain_hash"].(string)

	proof := map[string]interface{}{
		"cdp_version":  "1.0",
		"capsule_id":   waveNCapsuleID,
		"destroyed_at": waveNTimestamp,
		"chain":        chain,
		"final_hash":   finalHash,
		"attestation": map[string]interface{}{
			"algorithm":           "Ed25519",
			"signing_key_version": "1",
		},
	}
	if nReceipts > 0 {
		proof["record_receipts"] = receipts
		if rrmrPtr != nil {
			proof["record_receipts_merkle_root"] = *rrmrPtr
		}
	}
	if len(parentSeeds) > 0 {
		proof["parent_proof_hashes"] = parents
		if ppmrPtr != nil {
			proof["parent_proofs_merkle_root"] = *ppmrPtr
		}
	}
	return proof
}

func TestFixture01N0NoReceiptsNoParentsByteEquivalentBaseline(t *testing.T) {
	proof := buildWaveNProof(0, nil)
	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if !result.Valid {
		t.Fatalf("N=0 Wave-N proof MUST verify (pre-Wave-N baseline); got %+v", result)
	}
	if _, has := proof["record_receipts"]; has {
		t.Errorf("N=0 must NOT carry record_receipts")
	}
	if _, has := proof["parent_proof_hashes"]; has {
		t.Errorf("N=0 must NOT carry parent_proof_hashes")
	}
}

func TestFixture02N1SingleReceipt(t *testing.T) {
	proof := buildWaveNProof(1, nil)
	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if !result.Valid {
		t.Errorf("N=1 receipt MUST verify; got %+v", result)
	}
}

func TestFixture03N2TwoReceipts(t *testing.T) {
	proof := buildWaveNProof(2, nil)
	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if !result.Valid {
		t.Errorf("N=2 receipts MUST verify; got %+v", result)
	}
}

func TestFixture04N10TenReceipts(t *testing.T) {
	proof := buildWaveNProof(10, nil)
	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if !result.Valid {
		t.Errorf("N=10 receipts MUST verify; got %+v", result)
	}
}

func TestFixture05N100HundredReceipts(t *testing.T) {
	proof := buildWaveNProof(100, nil)
	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if !result.Valid {
		t.Errorf("N=100 receipts MUST verify; got %+v", result)
	}
}

func TestFixture06N1000ThousandReceipts(t *testing.T) {
	proof := buildWaveNProof(1000, nil)
	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if !result.Valid {
		t.Errorf("N=1000 receipts MUST verify; got %+v", result)
	}
}

func TestFixture07ParentDepth1(t *testing.T) {
	proof := buildWaveNProof(1, [][]string{{"input-data", "banjo"}})
	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if !result.Valid {
		t.Errorf("depth-1 parent MUST verify; got %+v", result)
	}
}

func TestFixture08ParentDepth4(t *testing.T) {
	proof := buildWaveNProof(2, [][]string{
		{"input-data", "banjo"},
		{"rag-retrieval", "llamaindex"},
		{"safety-review", "guardrails"},
		{"output-validation", "anterior"},
	})
	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if !result.Valid {
		t.Errorf("depth-4 parents MUST verify; got %+v", result)
	}
}

func TestFixture09CyclicParentRejected(t *testing.T) {
	// Build happy-path proof, then mutate the single parent to be a
	// self-reference. Update parent_proofs_merkle_root so the parent-root
	// check at stage 3 passes; the chain-walk then detects mismatch at step 8.
	proof := buildWaveNProof(1, [][]string{{"input-data", "banjo"}})
	chain := proof["chain"].([]interface{})
	step8 := chain[7].(map[string]interface{})["chain_hash"].(string)

	cyclicParent := map[string]interface{}{
		"parent_chain_hash":       "sha512:" + step8,
		"parent_key_id":           "cust-auth-self-cycle",
		"parent_signature":        "base64:malicious",
		"parent_role":             "self-loop",
		"parent_jurisdiction":     "US",
		"parent_organization_tag": "vendor:cyclic",
	}
	proof["parent_proof_hashes"] = []interface{}{cyclicParent}
	proof["parent_proofs_merkle_root"] = "sha512:" + step8

	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if result.Valid {
		t.Errorf("Cyclic parent MUST be rejected; got %+v", result)
	}
}

func TestFixture10MissingSignatureParentAcceptedStructurally(t *testing.T) {
	proof := buildWaveNProof(1, [][]string{{"input-data", "banjo"}})
	parents := proof["parent_proof_hashes"].([]interface{})
	p0 := parents[0].(map[string]interface{})
	p0["parent_signature"] = ""

	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	// Wave A scope: per-link signature NOT checked; Merkle root binding intact.
	if !result.Valid {
		t.Errorf("missing-signature parent verifies STRUCTURALLY at Wave A; got %+v", result)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Tamper-rejection regression
// ─────────────────────────────────────────────────────────────────────────────

func TestRegressionTamperedRecordMerkleRootRejected(t *testing.T) {
	proof := buildWaveNProof(5, nil)
	proof["record_receipts_merkle_root"] = "sha512:" + strings.Repeat("f", 128)
	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if result.Valid {
		t.Errorf("Tampered record Merkle root MUST be rejected")
	}
}

func TestRegressionTamperedReceiptChainHashRejected(t *testing.T) {
	proof := buildWaveNProof(3, nil)
	receipts := proof["record_receipts"].([]interface{})
	receipts[1].(map[string]interface{})["record_chain_hash"] = "sha512:" + strings.Repeat("f", 128)

	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if result.Valid {
		t.Errorf("Tampered receipt chain hash MUST be rejected")
	}
}

func TestRegressionSwappedPatternTagRejected(t *testing.T) {
	// The fixture binds "pa" into receipt 0's chain hash; swapping the JSON
	// field after emission MUST break the recompute (ADR-039 signed primitive).
	proof := buildWaveNProof(3, nil)
	receipts := proof["record_receipts"].([]interface{})
	receipts[0].(map[string]interface{})["pattern_tag"] = "custom"

	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if result.Valid {
		t.Errorf("Swapped pattern_tag MUST invalidate the receipt chain hash")
	}
}

func TestRegressionStrippedPatternTagRejected(t *testing.T) {
	// Removing a declared tag falls back to the untagged formula, which
	// cannot reproduce a tagged chain hash (domain separation).
	proof := buildWaveNProof(1, nil)
	receipts := proof["record_receipts"].([]interface{})
	delete(receipts[0].(map[string]interface{}), "pattern_tag")

	jsonBytes, _ := json.Marshal(proof)
	result := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})
	if result.Valid {
		t.Errorf("Stripped pattern_tag MUST invalidate the receipt chain hash")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Forever-Standard byte-equivalence regression
// ─────────────────────────────────────────────────────────────────────────────

func TestForeverStandardPreWaveNProofByteIdentical(t *testing.T) {
	// Pre-Wave-N proof (no record_receipts, no parent_proof_hashes) MUST
	// produce identical chain hashes when verified by the Wave-N pipeline,
	// because Step 8 collapses to the legacy formula via (nil, nil) arm.
	subsystems := []string{
		"eee_namespace", "eee_tmpfs", "eee_memory", "dire_keys",
		"dire_identity", "fgx_forensic", "rzl_audit", "capsule_destroy",
	}
	prevHash := NanorixGenesisHash
	chain := make([]interface{}, 0, 8)
	for _, subsystem := range subsystems {
		method := LookupMethod(subsystem)
		chainHash := ComputeStepHash(prevHash, subsystem, "destroy", method, waveNTimestamp)
		chain = append(chain, map[string]interface{}{
			"subsystem":  subsystem,
			"method":     method,
			"chain_hash": chainHash,
		})
		prevHash = chainHash
	}
	finalHash := chain[7].(map[string]interface{})["chain_hash"].(string)

	preWaveN := map[string]interface{}{
		"cdp_version":  "1.0",
		"capsule_id":   waveNCapsuleID,
		"destroyed_at": waveNTimestamp,
		"chain":        chain,
		"final_hash":   finalHash,
	}
	jsonBytes, _ := json.Marshal(preWaveN)

	// Verify via both V1 + Wave-N pipelines — outputs MUST match exactly.
	v1 := Verify(jsonBytes, VerifierPolicy{})
	wn := VerifyFullAuditProofWaveN(jsonBytes, VerifierPolicy{})

	if !v1.Valid {
		t.Errorf("V1 pipeline must accept pre-Wave-N proof; got %+v", v1)
	}
	if !wn.Valid {
		t.Errorf("Wave-N pipeline must accept pre-Wave-N proof; got %+v", wn)
	}
	if v1.StageReached != wn.StageReached {
		t.Errorf("V1 + Wave-N stage_reached must match: v1=%d, wave_n=%d", v1.StageReached, wn.StageReached)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

func sha512Sum(b []byte) string {
	sum := sha512.Sum512(b)
	return hex.EncodeToString(sum[:])
}
