//! the boundary-attestation specification D7 — BoundaryAttestation offline verification tests.
//!
//! The anchor fixture (`fixtures/boundary/0001_single_signed.json`) was
//! generated BY HAND from the boundary-attestation specification D2 formula — hashes computed with
//! python3 hashlib, signature with a fixed Ed25519 test seed (32 × 0x2a) —
//! independently of this crate's Rust code. Regeneration recipe:
//! `fixtures/boundary/README.md`. The pinned constants below are the
//! hand-computed values; if the module ever drifts from the ADR formula,
//! these tests break loudly.

use nanorix_verify::{
    recompute_activity_commitment, recompute_boundary_canonical_hash, verify_boundary_attestation,
    verify_boundary_chain, verify_disclosed_activity_trail, BoundaryFailureReason, VerifierPolicy,
    BOUNDARY_CONTINUATION_STATEMENT, NANORIX_GENESIS_HASH,
};
use serde_json::{json, Value};

/// Hand-computed (python3 hashlib) SHA-512 over the fixture's JCS canonical
/// bytes (document minus `attestation` minus `canonical_hash`).
const FIXTURE_CANONICAL_HASH: &str = "7f8bc8f0cae035fffa2bf405495789ddbfa06216ae7284db319be3446fb42770f97d75a7d881c58a1f09cbe8d4d73c2e74468ef051b0e0c7a7c86af631ced975";

/// Hand-computed the per-record receipt specification-shaped commitment over the two disclosed events
/// below: prev = genesis; prev = SHA-512(prev ‖ 0x00 ‖ SHA-512(JCS(event)).hex()).
const FIXTURE_ACTIVITY_COMMITMENT: &str = "ed11da07af53a9c2477595f1390f5c41cabffa2db3e720644802a346b2f9e27cab4008556fd7b81374063c997bc3effab7c67f3f7f3e47ffd2056091638157ba";

/// The disclosed activity trail the fixture's commitment was computed over.
fn fixture_trail() -> Vec<Value> {
    vec![
        json!({"event": "exec", "seq": 1}),
        json!({"event": "output_read", "seq": 2}),
    ]
}

fn load_fixture() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/boundary/0001_single_signed.json"
    );
    let bytes = std::fs::read(path).expect("fixture must exist");
    serde_json::from_slice(&bytes).expect("fixture must be valid JSON")
}

/// The same fixed test seed the fixture was signed with (32 × 0x2a). RFC 8032
/// seed semantics are identical between python `cryptography` and
/// `ed25519_dalek`, so this reproduces the fixture keypair.
fn test_signing_key() -> ed25519_dalek::SigningKey {
    ed25519_dalek::SigningKey::from_bytes(&[42u8; 32])
}

fn b64(bytes: &[u8]) -> String {
    use base64::Engine as _;
    base64::engine::general_purpose::STANDARD.encode(bytes)
}

/// Recompute canonical hash, sign it with the test key, and install
/// `canonical_hash` + `attestation` on `doc` — the issuance-side mirror used
/// to build chain successors in these tests.
fn sign_doc(doc: &mut Value) {
    use ed25519_dalek::Signer as _;
    let key = test_signing_key();
    let canonical = recompute_boundary_canonical_hash(doc);
    let sig = key.sign(canonical.as_bytes());
    doc["canonical_hash"] = Value::String(format!("sha512:{canonical}"));
    doc["attestation"] = json!({
        "public_key": format!("base64:{}", b64(&key.verifying_key().to_bytes())),
        "signature": format!("base64:{}", b64(&sig.to_bytes())),
        "pqc_signature": null,
    });
}

/// A signed successor (index 2) chained onto `prev_doc`.
fn make_successor(prev_doc: &Value) -> Value {
    let prev_hash = recompute_boundary_canonical_hash(prev_doc);
    let mut doc = json!({
        "version": "1.0",
        "kind": "boundary_attestation",
        "capsule_id": prev_doc["capsule_id"],
        "attestation_index": 2,
        "cutoff_ts": "2026-08-08T13:00:00Z",
        "boundary_evidence": [
            {"surface": "namespace", "method": "procfs_observation", "observed": true},
            {"surface": "tmpfs", "method": "mountinfo_observation", "observed": true},
            {"surface": "cgroup_v2", "method": "cgroup_v2_observation", "observed": true},
        ],
        "activity_commitment": format!("sha512:{NANORIX_GENESIS_HASH}"),
        "activity_event_count": 0,
        "continuation": BOUNDARY_CONTINUATION_STATEMENT,
        "prev_attestation_hash": format!("sha512:{prev_hash}"),
        "hash_algorithm": "sha512",
        "signature_algorithm": "Ed25519",
        "authority_id": "us-kms-nanorix-v1",
        "signing_key_version": "1",
        "key_id": "nrx-boundary-2026-08-08T13-00-00Z-cap_bnd0",
    });
    sign_doc(&mut doc);
    doc
}

// ── Hand-computed pins: the module must reproduce the python values ────────

#[test]
fn canonical_recompute_matches_hand_computed_value() {
    let fixture = load_fixture();
    assert_eq!(
        recompute_boundary_canonical_hash(&fixture),
        FIXTURE_CANONICAL_HASH,
        "canonical recompute drifted from the hand-computed the boundary-attestation specification D2 value"
    );
}

#[test]
fn activity_commitment_matches_hand_computed_value() {
    assert_eq!(
        recompute_activity_commitment(&fixture_trail()),
        FIXTURE_ACTIVITY_COMMITMENT,
        "activity-commitment recompute drifted from the hand-computed the per-record receipt specification-shaped value"
    );
}

#[test]
fn empty_trail_commits_to_genesis() {
    assert_eq!(recompute_activity_commitment(&[]), NANORIX_GENESIS_HASH);
}

// ── Single-document verification ───────────────────────────────────────────

#[test]
fn fixture_verifies_with_signature_checked() {
    let fixture = load_fixture();
    let result = verify_boundary_attestation(&fixture, &VerifierPolicy::default());
    assert!(
        result.valid,
        "hand-built fixture must verify; got {result:?}"
    );
    assert!(result.signature_checked);
    assert!(
        !result.trust_anchored,
        "no manifest supplied → embedded-key integrity only"
    );
    assert_eq!(result.stage_reached, 3);
    assert_eq!(
        result.metadata.capsule_id.as_deref(),
        Some("cap_bnd_fixture_0001")
    );
    assert_eq!(result.metadata.attestation_index, Some(1));
    assert_eq!(result.metadata.activity_event_count, Some(2));
}

#[test]
fn tampered_cutoff_fails_canonical_hash_at_stage_2() {
    let mut doc = load_fixture();
    doc["cutoff_ts"] = Value::String("2026-08-08T18:00:00Z".into());
    let result = verify_boundary_attestation(&doc, &VerifierPolicy::default());
    assert!(!result.valid);
    assert_eq!(result.stage_reached, 2);
    assert!(matches!(
        result.failure_reason,
        Some(BoundaryFailureReason::CanonicalHashMismatch { .. })
    ));
}

#[test]
fn tamper_with_recomputed_canonical_hash_fails_signature_at_stage_3() {
    // An attacker who edits a field AND recomputes canonical_hash to match
    // moves the failure to the signature: the signed message no longer
    // corresponds to the document.
    let mut doc = load_fixture();
    doc["cutoff_ts"] = Value::String("2026-08-08T18:00:00Z".into());
    let recomputed = recompute_boundary_canonical_hash(&doc);
    doc["canonical_hash"] = Value::String(format!("sha512:{recomputed}"));
    let result = verify_boundary_attestation(&doc, &VerifierPolicy::default());
    assert!(!result.valid);
    assert_eq!(result.stage_reached, 3);
    assert!(matches!(
        result.failure_reason,
        Some(BoundaryFailureReason::SignatureMismatch { .. })
    ));
}

#[test]
fn unsigned_document_is_valid_but_signature_unchecked() {
    // The library-level analog of CLI exit 3 (the published corpus ladder): the
    // canonical form verified, but integrity is NOT established, and the
    // caller must never map this to exit 0.
    let mut doc = load_fixture();
    doc.as_object_mut().unwrap().remove("attestation");
    let result = verify_boundary_attestation(&doc, &VerifierPolicy::default());
    assert!(result.valid);
    assert!(!result.signature_checked);
    assert_eq!(result.stage_reached, 2);
}

#[test]
fn destruction_chain_method_name_is_rejected_as_vocabulary_violation() {
    // the boundary-attestation specification D2: observation vocabulary is disjoint from the 8
    // destruction-chain method names — a snapshot must never carry a string
    // that could be mistaken for a destruction step.
    let mut doc = load_fixture();
    doc["boundary_evidence"][0]["method"] = Value::String("procfs_verification".into());
    let result = verify_boundary_attestation(&doc, &VerifierPolicy::default());
    assert!(!result.valid);
    assert_eq!(result.stage_reached, 1);
    assert!(matches!(
        result.failure_reason,
        Some(BoundaryFailureReason::MethodVocabularyViolation { .. })
    ));
}

#[test]
fn altered_continuation_statement_is_rejected_at_stage_1() {
    // Even with a consistently recomputed canonical hash (unsigned doc), a
    // missing/altered not-a-destruction-claim statement fails typed.
    let mut doc = load_fixture();
    doc.as_object_mut().unwrap().remove("attestation");
    doc["continuation"] = Value::String("This capsule was destroyed.".into());
    let recomputed = recompute_boundary_canonical_hash(&doc);
    doc["canonical_hash"] = Value::String(format!("sha512:{recomputed}"));
    let result = verify_boundary_attestation(&doc, &VerifierPolicy::default());
    assert!(!result.valid);
    assert_eq!(result.stage_reached, 1);
    assert_eq!(
        result.failure_reason,
        Some(BoundaryFailureReason::ContinuationStatementMismatch)
    );
}

#[test]
fn wrong_kind_and_unknown_version_fail_typed() {
    let mut doc = load_fixture();
    doc["kind"] = Value::String("audit_proof".into());
    let result = verify_boundary_attestation(&doc, &VerifierPolicy::default());
    assert!(matches!(
        result.failure_reason,
        Some(BoundaryFailureReason::KindMismatch { .. })
    ));

    let mut doc = load_fixture();
    doc["version"] = Value::String("9.9".into());
    let result = verify_boundary_attestation(&doc, &VerifierPolicy::default());
    assert!(matches!(
        result.failure_reason,
        Some(BoundaryFailureReason::VersionUnsupported { .. })
    ));
}

// ── Chain walk (the boundary-attestation specification D5 / D7 stage 4) ───────────────────────────────────

#[test]
fn two_attestation_chain_verifies_genesis_anchored() {
    let att1 = load_fixture();
    let att2 = make_successor(&att1);
    // Supplied out of order on purpose: the walk orders by attestation_index.
    let result = verify_boundary_chain(&[att2, att1], &VerifierPolicy::default());
    assert!(result.valid, "chain must verify; got {result:?}");
    assert_eq!(result.chain_span, Some((1, 2)));
    assert!(result.genesis_anchored);
    assert!(result.all_signatures_checked);
    assert_eq!(result.per_document.len(), 2);
}

#[test]
fn broken_prev_hash_linkage_is_rejected() {
    let att1 = load_fixture();
    let mut att2 = make_successor(&att1);
    att2["prev_attestation_hash"] = Value::String(format!("sha512:{}", "0".repeat(128)));
    sign_doc(&mut att2); // re-signed so ONLY the linkage is wrong
    let result = verify_boundary_chain(&[att1, att2], &VerifierPolicy::default());
    assert!(!result.valid);
    assert_eq!(result.failed_at_index, Some(2));
    assert!(matches!(
        result.failure_reason,
        Some(BoundaryFailureReason::PrevAttestationHashMismatch { index: 2, .. })
    ));
}

#[test]
fn index_gap_is_rejected() {
    let att1 = load_fixture();
    let mut att3 = make_successor(&att1);
    att3["attestation_index"] = json!(3); // deleted snapshot 2 → gap
    sign_doc(&mut att3);
    let result = verify_boundary_chain(&[att1, att3], &VerifierPolicy::default());
    assert!(!result.valid);
    assert!(matches!(
        result.failure_reason,
        Some(BoundaryFailureReason::IndexNotStrictlyIncremented {
            prev_index: 1,
            index: 3
        })
    ));
}

#[test]
fn non_increasing_cutoff_is_rejected() {
    let att1 = load_fixture();
    let mut att2 = make_successor(&att1);
    att2["cutoff_ts"] = Value::String("2026-08-08T11:00:00Z".into()); // before att1's cutoff
    sign_doc(&mut att2);
    let result = verify_boundary_chain(&[att1, att2], &VerifierPolicy::default());
    assert!(!result.valid);
    assert!(matches!(
        result.failure_reason,
        Some(BoundaryFailureReason::CutoffNotIncreasing { .. })
    ));
}

#[test]
fn cross_capsule_chain_is_rejected() {
    let att1 = load_fixture();
    let mut att2 = make_successor(&att1);
    att2["capsule_id"] = Value::String("cap_other_capsule".into());
    sign_doc(&mut att2);
    let result = verify_boundary_chain(&[att1, att2], &VerifierPolicy::default());
    assert!(!result.valid);
    assert!(matches!(
        result.failure_reason,
        Some(BoundaryFailureReason::CapsuleIdMismatch { .. })
    ));
}

#[test]
fn genesis_rule_enforced_at_index_1() {
    let mut att1 = load_fixture();
    att1["prev_attestation_hash"] = Value::String(format!("sha512:{}", "0".repeat(128)));
    sign_doc(&mut att1);
    let result = verify_boundary_chain(&[att1], &VerifierPolicy::default());
    assert!(!result.valid);
    assert!(matches!(
        result.failure_reason,
        Some(BoundaryFailureReason::GenesisPrevHashMismatch { .. })
    ));
}

#[test]
fn suffix_without_origin_verifies_but_is_not_genesis_anchored() {
    // A verifier holding only a suffix of the chain can check its internal
    // consistency; the unverifiable head link is reported structurally, never
    // silently upgraded (the boundary-attestation specification D5).
    let att1 = load_fixture();
    let att2 = make_successor(&att1);
    let result = verify_boundary_chain(&[att2], &VerifierPolicy::default());
    assert!(
        result.valid,
        "suffix must verify internally; got {result:?}"
    );
    assert!(!result.genesis_anchored);
    assert_eq!(result.chain_span, Some((2, 2)));
}

// ── Disclosed activity trail (the boundary-attestation specification D7 stage 5) ──────────────────────────

#[test]
fn disclosed_trail_matches_fixture_commitment() {
    let fixture = load_fixture();
    assert_eq!(
        verify_disclosed_activity_trail(&fixture, &fixture_trail()),
        None,
        "the hand-computed trail must recompute to the fixture's commitment"
    );
}

#[test]
fn short_trail_fails_event_count() {
    let fixture = load_fixture();
    let events = fixture_trail();
    let trail = &events[..1];
    assert!(matches!(
        verify_disclosed_activity_trail(&fixture, trail),
        Some(BoundaryFailureReason::ActivityEventCountMismatch {
            claimed: 2,
            actual: 1
        })
    ));
}

#[test]
fn tampered_event_fails_commitment() {
    let fixture = load_fixture();
    let mut trail = fixture_trail();
    trail[1]["event"] = Value::String("output_read_tampered".into());
    assert!(matches!(
        verify_disclosed_activity_trail(&fixture, &trail),
        Some(BoundaryFailureReason::ActivityCommitmentMismatch { .. })
    ));
}
